## **`ESTRUCTURAS DEL PROYECTO`**

### ESTRUCTURAS DE CARPETAS Y COMENTARIOS VARIOS


**Estructura de Carpetas**<br>
data/raw -> Datos originales. Nunca modificar.<br>
data/processed -> Datos limpios y preparados.<br>
docs -> Documentacion del proyecto (instrucciones, rúbricas, enunciados), que no es dato ni código ni informe final.<br>
notebooks -> Aprendizaje y análisis.<br>
reports -> Informes finales.<br>
dashboard -> Aplicación Streamlit.<br>
src -> Código reutilizable.<br>
<br>
**Git y GitHub**<br>
git init -> Inicializar Git.<br>
git clone URL -> Clonar repositorio.<br>
code . -> Abrir en VS Code.<br>
git add . -> Preparar cambios.<br>
git commit -m -> Guardar versión.<br>
git push -> Subir cambios.<br>
git pull -> Descargar cambios.<br>
git remote -v -> Ver remoto.<br>
git remote remove origin -> Quitar remoto.<br>
Remove-Item -Recurse -Force .git -> Desconectar proyecto de Git<br>
   cd “..\carpeta a cambiar” ->.  Para cambiar de carpeta<br>
<br>
**Framework**<br>
sp_integracion.py<br>
sp_carga_exploracion.py<br>
sp_limpieza_transformacion.py<br>
sp_eda.py<br>
sp_imputacion_avanzada.py<br>
sp_abtest.py<br>
sp_modelado.py<br>
sp_clustering.py<br>
sp_series_temporales.py<br>
<br>
**Soportes src**<br>
soporte_utils.py -> Funciones auxiliares.<br>
soporte_utils_visual.py -> Funciones auxiliares visualizacion<br>
soporte_utils_ml.py-> Funciones auxiliares ml<br>
<br>
**Notebooks un solo tipo de modelo (la mayoría de proyectos)**<br>
crear_estructura. ipynb<br>
integracion.ipynb<br>
<br>
00_consultas_referencia.ipynb<br>
01_carga_exploracion.ipynb<br>
02_limpieza_transformacion.ipynb<br>
03_eda.ipynb<br>
04_abtest.ipynb<br>
05_modelado.ipynb<br>
06_clustering.ipynb<br>
07_series_temporales.ipynb<br>
08_dashboard.ipynb<br>
<br>
**Notebooks para dataset con doble objetivo**<br>
crear_estructura. ipynb<br>
integracion.ipynb<br>

00_consultas_referencia.ipynb<br>
01_carga_exploracion.ipynb<br>
02_limpieza_transformacion.ipynb<br>
03_eda.ipynb<br>
04_abtest.ipynb<br>
05_preprocesamiento.ipynb<br>
06_regresion.ipynb<br>
06_clasificacion.ipynb<br> 
07_clustering.ipynb<br>
08_series_temporales.ipynb<br>
09_dashboard.ipynb<br>

**USOS DE DF** 
- UNIVARIABLE --> usar grupos temáticos
- BIVARIABLE CON TV --> usar df_origen
- CORRELACIONES --> usar df_origen    
- MODELADO --> usar df_origen

<br>
-- `*CORRELACIONES*` <br>
**Numéricas**<br>
groupby('objetivo').mean()<br>
**Categóricas**<br>
crosstab(col, objetivo, normalize='index')

0️⃣ 1️⃣ 2️⃣ 3️⃣ 4️⃣ 5️⃣ 6️⃣ 7️⃣ 8️⃣ 9️⃣ 🔟

### ESTRUCTURA DE NOTEBOOKS

#### 01_carga_exploracion.ipynb
---

In [ ]:
## 0️. Importar Librerias

## 1️. Cargar DataFrame 

## 2. Exploración Inicial
    ### exploracion inicial()

#### 02_limpieza_transformacion.ipynb
---

In [ ]:
## 0️. Importar Librerias

## 1️. Cargar DataFrame 
    ### Cargar DataFrame original df_o
    ###  df_l copia del df_o

## 2. Reporte de calidad de Datos
    ### reporte_calidad()

## 3. Normalizar Columnas
    ### eliminar_columnas()
    ### limpiar_columnas()
    ### renombrar_columnas()

## 4. Corregir tipos de Datos
    ### reemplazar_caracter()
    ### convertir_fecha()
    ### convertir_int()
    ### convertir_float()
    ### convertir_datetime()
    ### convertir_category()
    ### convertir_bool()

## 5. Tratar valores nulos
    ### buscar_nulos()
    ### columnas_con_nulos()
    ### estadisticas_nulos()
    ### analizar_nulos_numericas()
    ### analizar_nulos_categoricas()
    ### analizar_nulos_datetime()
    #### imputar_media()
    #### imputar_mediana()
    #### imputar_moda()
    #### imputar_constante()
    #### eliminar_filas_nulas()
    #### eliminar_columnas_nulas()

## 6. Eliminar duplicados
    ### buscar_duplicados()
    ### eliminar_duplicados()

## 7. Limpiar texto inconsistente
    ### ver_valores_string()
    ### limpiar_texto()
    ### reemplazar_texto()
    ### reemplazar_texto_dic()
    ### eliminar_acentos()
    ### insertar_columna_dic()

## 8. Revisión de variables
    ### buscar_constantes()
    ### buscar_columnas_vacias()
    ### buscar_ids()
    ### buscar_alta_cardinalidad()

## 9. Reglas de negocio
    ### Validaciones específicas de cada dataset
    ### Consultar plantilla en sp_utils.py

## 10. Detectar y tratar outliers
    ### detectar_outliers_todas()
    ### detectar_outliers_iqr()
    ### eliminar_outliers_iqr()
    ### winsorizar_columnas()

## 11. Preparación para ML (opcional)
    ### crear_binaria_sn()
    ### preparar_binaria_ml()
    ### crear_binaria_ml()

## 12. Validación final - Guardado
    ### validacion_final()
    ### guardar_csv()

#### 03_eda.ipynb
---

In [ ]:
## 0️ IMPORTAR LIBRERIAS

## 1️. CARGA DATAFRAME 
    ### CARGAR DF ORIGINAL
    ###  COPIA DEL DF ORIGINAL
  
   

## 2️. EDA PRELIMINAR
    ###  EXPLORACION DEL DATA FRAME
    ###  ANALISIS DE VARIABLES DEL DATA FRAME
        #### cols_excluir

## 3️ GRUPOS TEMATICOS
    ### Renombrar dataframe 
    ### CREACION DE TABLAS TEMATICAS
    ### VARIABLES OBJETIVO y COLUMNAS EXCLUIR
    ### VARIABLES DATATIME
    ### Tasa de conversion global

## A. SUBRUPO W   ## B. SUBRUPO X   ## C. SUBRUPO Y  ## D. SUBRUPO Z
    ### Dataframe W / X / Y / Z
    ### COLUMNAS NUMERICAS    ### COLUMNAS CATEGORICAS  
        #### 1. EDA BASICO (Visualizacion del Dataframe)
        #### 2. ANALISIS POR TIPOS DE COLUMNAS
            ##### CLASIFICACION DE COLUMNAS
            #####  `columna`
        #### 3. ANALISIS DE CORRELACION CON VARIABLE OBJETIVO
        #### 4. EDA BIVARIANTE — (Analisis Bivariante)
            ##### `columna` vs `tv2`
        #### 5. SEGMENTACIONES 
                #####  Segmentación numérica (pd.cut) sp.utils 24
                #####  Segmentación categórica
                #####  Segmentación combinada
## 4. EDA GLOBAL
    ### MATRIZ DE CORRELACIÓN
    ### COMPARACIÓN DE GRUPOS
        #### exploracion_grupos()
    ### SEGMENTACIONES GLOBALES (Opcional)
    ### PREGUNTAS DE NEGOCIO (Opcional)

## 5. Validación final - Guardado
    ### validacion_final()
    ### guardar_csv()

#### 04_abtest.ipynb
---

In [ ]:
# FASE 4 — Análisis Inferencial (A/B Testing)
## 0️. Importar Librerias

## 1️. Cargar DataFrame 
    ###  df_a copia del df_o

## 2. CLASIFICAR COLUMNAS CONTROL - METRICAS 

    ## COMPARACIÓN DE GRUPOS
        #### exploracion_grupos()

## 3. EXPLORACIÓN DE GRUPOS
    #####  `col_control`y 
    ##### 'metricas'
    #####  `columna`
## 4. FLUJO DE COMPARACIÓN DE GRUPOS
    ### Normalidad
    ### homocedasticidad
    ### ttes_dos_grupos
    ### mannwhitneyu
    ### anova_tukey
    ### kruskal
    ### decidir_test

# 4. ANEXO — TESTS DE RELACIÓN ENTRE VARIABLES (no comparan grupos)
    ### intervalo_confianza_media
    ### chi_cuadrado_independencia
    ### correlacion_regresion

#### 05_modelado.ipynb
---

In [ ]:
### 0️. Importar Librerias

### 1️. Cargar DataFrame 
    ####  ... copia del df

### 2. Análisis de Datos
    #### clasificar_columnas()

### 3. Preparación de Datos
    #### preparacion_dataframe()

### 4. Separar Variables
    #### Variables para modelado
    #### Crear dataframe para modelado
    #### separar_xy()

### 5. Transformación de Variables
    #### nulos 
    #### tratar_numericas()
    #### codificar_binarias()
    #### codificar_categoricas()

### 6. División Train/Test
    #### train_test()

### 7. Estandarización
    #### estandarizar()

### 8. Entrenamiento Incial
    #### entrenar_evaluar_clasificacion()
    #### entrenar_evaluar_regresion()

### 9. Métricas
    #### metricas_clasificacion()
    #### metricas_regresion()

### 10. Validacion
    #### comparar_train_test()

### 11. Comparación de modelos
    #### comparar_modelos()

### 12. Optimización
    #### grid_search()
    # Repeticion de pasos
    #### Optimización: entrenar_evaluar_clasificacion()
    #### Optimización: entrenar_evaluar_regresión()
    #### Optimización: comparar_train_test()

### 13. Entrenamiento Final
    #### entrenar_final()

### 14. Interpretación
    #### importancia_variables()

### 15. Simulación
    ### X_train.describe().round(2).T
    #### simular_variable()

### 16. Predicciones
    #### predecir()

### 17. Guardar Modelo 
    #### guardar_modelo()

### 18. Cargar Modelo
    #### cargar_modelo()

## **`DATOS DEL PROYECTO`**

### 0️ Importar Librerias

In [1]:
import sys
from pathlib import Path

sys.path.append(str(Path().resolve().parent))

In [2]:
# Tratamiento de Datos
import pandas as pd
import numpy as np
from IPython.display import display

# Visualizaciones
import matplotlib.pyplot as plt
import seaborn as sns

# Para que se muestren todas las columnas al inspeccionar los DataFrames
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 2000)
pd.set_option('display.expand_frame_repr', False)
pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_rows', None)

In [5]:
from framework import sp_carga_exploracion as sc
from framework import sp_limpieza_transformacion as sl
from framework import sp_eda as se
from framework import sp_abtest as sb
# from framework import sp_modelado as sm
# from framework import sp_clustering as cl
# from framework import sp_series_temporales as st
# from framework import sp_imputacion_avanzada as sa

### Carga DataFrame Original

In [13]:
ruta = (r"../data/raw/dataset_estudiantes.csv")
df_o = sc.leer_csv(ruta)

======================================================================
CSV CARGADO
======================================================================
Archivo: ../data/raw/dataset_estudiantes.csv
Filas:   1000
Columnas: 11
======================================================================

#### exploracion inicial

In [14]:
sc.exploracion_inicial(df_o)

5 FILAS ALEATORIAS

                                         452        588        545
horas_estudio_semanal               5.723566   4.927144   6.176452
nota_anterior                      78.552414  61.314408  78.909093
tasa_asistencia                    84.899419  74.824358  90.026654
horas_sueno                         5.956138   7.043289   5.304224
edad                                      21         18         27
nivel_dificultad                     Difícil    Difícil      Medio
tiene_tutor                               No         No         No
horario_estudio_preferido              Noche     Mañana      Noche
estilo_aprendizaje         Lectura/Escritura     Visual   Auditivo
nota_final                              66.1       59.9       71.1
aprobado                                   1          0          1

====================================================================================================
DIMENSIONES
El número de filas es: 1000 filas
El número de columnas es: 11 columnas
====================================================================================================
INFORMACION BASICA
<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   horas_estudio_semanal      1000 non-null   float64
 1   nota_anterior              1000 non-null   float64
 2   tasa_asistencia            1000 non-null   float64
 3   horas_sueno                850 non-null    float64
 4   edad                       1000 non-null   int64
 5   nivel_dificultad           1000 non-null   str
 6   tiene_tutor                1000 non-null   str
 7   horario_estudio_preferido  900 non-null    str
 8   estilo_aprendizaje         950 non-null    str
 9   nota_final                 1000 non-null   float64
 10  aprobado                   1000 non-null   int64
dtypes: float64(5), int64(2), str(4)
memory usage: 108.0 KB
None
====================================================================================================
COLUMNAS CON VALORES NULOS
horas_sueno                  150
horario_estudio_preferido    100
estilo_aprendizaje            50
dtype: int64
====================================================================================================
PORCENTAJES DE COLUMNAS CON VALORES NULOS
horas_sueno                  15.0
horario_estudio_preferido    10.0
estilo_aprendizaje            5.0
dtype: float64
====================================================================================================
VALORES DUPLICADOS
0
====================================================================================================
CONTEO COLUMNAS CATEGORIAS
NIVEL_DIFICULTAD
nivel_dificultad
Medio      504
Fácil      313
Difícil    183
Name: count, dtype: int64
TIENE_TUTOR
tiene_tutor
No    597
Sí    403
Name: count, dtype: int64
HORARIO_ESTUDIO_PREFERIDO
horario_estudio_preferido
Noche     344
Tarde     337
Mañana    219
Name: count, dtype: int64
ESTILO_APRENDIZAJE
estilo_aprendizaje
Visual               363
Auditivo             254
Kinestésico          178
Lectura/Escritura    155
Name: count, dtype: int64
====================================================================================================
ESTADISTICOS CATEGÓRICOS

                          count unique     top freq
nivel_dificultad           1000      3   Medio  504
tiene_tutor                1000      2      No  597
horario_estudio_preferido   900      3   Noche  344
estilo_aprendizaje          950      4  Visual  363

ESTADISTICOS NUMÉRICAS

                        count       mean        std   min        25%        50%        75%    max
horas_estudio_semanal  1000.0  10.072366   4.852218   1.0   6.627548  10.000000  13.372452   25.0
nota_anterior          1000.0  69.885456  14.687697  30.0  59.882644  70.000000  80.117356  100.0
tasa_asistencia        1000.0  73.992079  18.195948  20.0  61.510192  75.000000  88.489808  100.0
horas_sueno             850.0   7.007670   1.444790   4.0   5.995341   7.020701   8.018834   10.0
edad                   1000.0  23.532000   3.476933  18.0  21.000000  24.000000  27.000000   29.0
nota_final             1000.0  71.441400   9.562078  30.0  64.775000  71.400000  77.900000  100.0
aprobado               1000.0   0.898000   0.302800   0.0   1.000000   1.000000   1.000000    1.0

#### reporte_calidad()

In [15]:
sl.reporte_calidad(df_o)

                              tipo                                                    ejemplos
horas_estudio_semanal      float64  [8.957475998038344, 11.042524001961656, 4.510776081457513]
nota_anterior              float64   [48.83060095398218, 80.82570664326124, 90.38369427718838]
tasa_asistencia            float64   [86.64018172631499, 83.44965544904211, 74.62360717097394]
horas_sueno                float64   [6.675694179152657, 4.616843562140823, 7.755246085587813]
edad                         int64                                                [25, 18, 23]
nivel_dificultad               str                                     [Fácil, Difícil, Medio]
tiene_tutor                    str                                                    [Sí, No]
horario_estudio_preferido      str                                      [Tarde, Mañana, Noche]
estilo_aprendizaje             str                       [Lectura/Escritura, Visual, Auditivo]
nota_final                 float64                                          [84.4, 72.0, 80.0]
aprobado                     int64                                                      [1, 0]

### Carga DataFrame Limpio

In [ ]:
ruta = r"C:\Users\equipo\Desktop\THE POWER\xxxxxx\data\processed\02_datos_limpios.csv"
df_l = sc.leer_csv(ruta,parse_dates=['xxxxx'])

#### FUNCION EDA CONSULTAS DEL DATAFRAME

In [ ]:
# EDA CONSULTAS DEL DATA FRAME
def eda_consultas(df, cols_excluir=None):
    """
    Funcion que proporciona un EDA rapido.Realizado en consultas_referencias.

    Parameters
    ----------
    df : DataFrame
        DataFrame que queremos analizar.

    n : int
        Numero de decimales para las estadisticas numericas.

    cols_excluir : list
        Lista de columnas que no queremos analizar.
    """

    # Si no indicamos columnas a excluir,
    # creamos una lista vacia
    if cols_excluir is None:
        cols_excluir = []

    # Creamos un DataFrame sin las columnas excluidas
    df_eda = df.drop(columns=cols_excluir, errors="ignore")

    # --------------------------------------------------
    # IDENTIFICACION DE TIPOS DE COLUMNAS
    # --------------------------------------------------

    num_cols = df_eda.select_dtypes(
        include="number"
    ).columns

    cat_cols = df_eda.select_dtypes(
        include=["string", "category", "object"]
    ).columns

    date_cols = df_eda.select_dtypes(
        include=["datetime", "datetimetz"]
    ).columns

    # Mostramos las columnas encontradas
    print("VARIABLES NUMERICAS:\n\n", num_cols)
    print('=' * 100)

    print("\nVARIABLES CATEGORICAS:\n\n", cat_cols)
    print('=' * 100)

    print("\nVARIABLES DATETIME(FECHA):\n\n", date_cols)

    # --------------------------------------------------
    # ESTADISTICAS BASICAS
    # --------------------------------------------------

    print("\n========== ESTADÍSTICAS BÁSICAS ==========\n")

    # Variables numericas
    if len(num_cols) > 0:

        print("VARIABLES NUMERICAS:")

        print(
            df_eda[num_cols]
            .describe()
            .T
            .round(2)
        )

    # Variables categoricas
    if len(cat_cols) > 0:

        print("\nVARIABLES CATEGORICAS:")

        print(
            df_eda[cat_cols]
            .describe()
            .T
        )

    # Variables datetime
    if len(date_cols) > 0:

        print("\nVARIABLES DATETIME(FECHA):")

        print(
            df_eda[date_cols]
            .describe()
            .T
        )

    # --------------------------------------------------
    # ANALISIS DE VARIABLES CATEGORICAS
    # --------------------------------------------------

    if len(cat_cols) > 0:

        print(
            "\n========== ANALISIS DE VARIABLES CATEGORICAS ==========\n"
        )

        for col in cat_cols:

            print(
                f"\n----------- ESTAMOS ANALIZANDO: '{col}' ----------\n"
            )

            print("Valores únicos:")

            print(
                df_eda[col].unique()
            )

            print("\nFrecuencia de los valores:")

            print(
                df_eda[col].value_counts()
            )

    # --------------------------------------------------
    # COUNTPLOT
    # --------------------------------------------------

    if len(cat_cols) > 0:

        print(
            "\n============== COUNTPLOT ==============\n"
            "(REPRESENTACIÓN DE UNIVARIABLES CATEGÓRICAS)"
        )

        # Si tiene demasiadas categorias,
        # no hacemos el grafico
        cat_cols_plot = [
            col for col in cat_cols
            if df_eda[col].nunique() <= 200
        ]

        # Mostramos las columnas que no se van a representar
        for col in cat_cols:

            if df_eda[col].nunique() > 200:

                print(
                    f"Columna {col} tiene demasiadas "
                    f"categorias: {df_eda[col].nunique()}"
                )

        # Creamos los graficos solo si hay columnas que representar
        if len(cat_cols_plot) > 0:

            n_graficos = len(cat_cols_plot)
            ncols = 2
            nrows = (n_graficos + ncols - 1) // ncols

            fig, axes = plt.subplots(
                nrows,
                ncols,
                figsize=(8 * ncols, 5 * nrows)
            )

            axes = np.atleast_1d(axes).flatten()

            for ax, col in zip(axes, cat_cols_plot):

                sns.countplot(
                    x=df_eda[col],
                    order=df_eda[col].value_counts().index,
                    ax=ax
                )

                ax.set_title(f"Distribución de {col}")
                ax.tick_params(axis="x", rotation=90)

            # Ocultamos ejes sobrantes
            for ax in axes[n_graficos:]:
                ax.set_visible(False)

            plt.tight_layout()
            plt.show()

    # --------------------------------------------------
    # HISTOGRAMAS
    # --------------------------------------------------

    if len(num_cols) > 0:
        print(
            "\n============== HISTOGRAMAS ==============\n"
            "(REPRESENTACION DE UNIVARIABLES NUMERICAS):"
        )

        n_graficos = len(num_cols)
        ncols = 3
        nrows = (n_graficos + ncols - 1) // ncols

        fig, axes = plt.subplots(
            nrows,
            ncols,
            figsize=(5 * ncols, 3.5 * nrows)
        )

        axes = np.atleast_1d(axes).flatten()

        for ax, col in zip(axes, num_cols):

            sns.histplot(
                df_eda[col],
                bins=20,
                ax=ax
            )

            ax.set_title(col)

        # Ocultamos ejes sobrantes
        for ax in axes[n_graficos:]:
            ax.set_visible(False)

        plt.tight_layout()
        plt.show()

    # --------------------------------------------------
    # BOXPLOTS
    # --------------------------------------------------

    if len(num_cols) > 0:

        print(
            "\n============== BOXPLOTS ==============\n"
            "(REPRESENTACION DE UNIVARIABLES NUMERICAS - OUTLIERS)"
        )

        n_graficos = len(num_cols)
        ncols = 1
        nrows = (n_graficos + ncols - 1) // ncols

        fig, axes = plt.subplots(
            nrows,
            ncols,
            figsize=(10 * ncols, 2 * nrows)
        )

        axes = np.atleast_1d(axes).flatten()

        for ax, col in zip(axes, num_cols):

            sns.boxplot(
                x=df_eda[col],
                ax=ax
            )

            ax.set_title(col)

        # Ocultamos ejes sobrantes
        for ax in axes[n_graficos:]:
            ax.set_visible(False)

        plt.tight_layout()
0        plt.show()

## **`HALLAZGOS_REFERENCIAS`**

### `01_carga_exploracion.ipynb`
---

DIMENSIONES: <br>
El número de filas es: 1000 filas <br>
El número de columnas es: 11 columnas

COLUMNAS CON VALORES NULOS <br>
horas_sueno                  150<br>
horario_estudio_preferido    100<br>
estilo_aprendizaje            50<br>

PORCENTAJES DE COLUMNAS CON VALORES NULOS <br>
horas_sueno                  15.0<br>
horario_estudio_preferido    10.0<br>
stilo_aprendizaje            5.0<br>

0 DUPLICADOS

EXPLORACION DE COLUMNAS<BR>
- tiene_tutor cambiar a tiene_tutor_sn y crear binaria tiene_tutor_ml
- aprobado cambiar a aprobado_ml y crear aprobado_sn string o categorica

### `02_LIMPIEZA`
---

##### Columna x

Hallazgo:<br>
- ... Key 

Decisión:<br>
- ...

Conclusión:<br>
- ...

Pendiente:<br>
- ...

### `03_EDA`
---

##### Columna x

Hallazgo:<br>
- ... Key 

Decisión:<br>
- ...

Conclusión:<br>
- ...

Pendiente:<br>
- ...

### `04_ABTEST`
---

##### Columna x

Hallazgo:<br>
- ... Key 

Decisión:<br>
- ...

Conclusión:<br>
- ...

Pendiente:<br>
- ...

---

### `05_MODELADO`
---

##### Columna x

Hallazgo:<br>
- ... Key 

Decisión:<br>
- ...

Conclusión:<br>
- ...

Pendiente:<br>
- ...

### `00_HALLAZGOS_DECISIONES`
---
---

##### Columna x

Ipynb_origen:Hallazgo(clave_busqueda):<br>
- ...