In [1]:
import sys
from pathlib import Path

sys.path.append(str(Path().resolve().parent))

In [2]:
# Tratamiento de Datos
import pandas as pd
import numpy as np
from IPython.display import display

# Visualizaciones
import matplotlib.pyplot as plt
import seaborn as sns

# Para que se muestren todas las columnas al inspeccionar los DataFrames
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 2000)
pd.set_option('display.expand_frame_repr', False)
pd.set_option('display.max_colwidth', None)

In [3]:
from framework import sp_carga_exploracion as sc

In [4]:
ruta = (r"../data/raw/dataset_estudiantes.csv")
df = sc.leer_csv(ruta)

======================================================================
CSV CARGADO
======================================================================
Archivo: ../data/raw/dataset_estudiantes.csv
Filas:   1000
Columnas: 11
======================================================================

In [5]:
sc.exploracion_inicial(df)

5 FILAS ALEATORIAS

                                   211        594          494
horas_estudio_semanal        10.787347       25.0     7.353495
nota_anterior                72.552771  73.320156    74.567229
tasa_asistencia                  100.0  82.741554    37.965325
horas_sueno                   6.805627   8.102197          4.0
edad                                23         22           22
nivel_dificultad                 Fácil      Medio        Medio
tiene_tutor                         No         Sí           No
horario_estudio_preferido        Tarde      Noche        Tarde
estilo_aprendizaje         Kinestésico   Auditivo  Kinestésico
nota_final                        81.1       77.7         63.1
aprobado                             1          1            1

====================================================================================================
DIMENSIONES
El número de filas es: 1000 filas
El número de columnas es: 11 columnas
====================================================================================================
INFORMACION BASICA
<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   horas_estudio_semanal      1000 non-null   float64
 1   nota_anterior              1000 non-null   float64
 2   tasa_asistencia            1000 non-null   float64
 3   horas_sueno                850 non-null    float64
 4   edad                       1000 non-null   int64
 5   nivel_dificultad           1000 non-null   str
 6   tiene_tutor                1000 non-null   str
 7   horario_estudio_preferido  900 non-null    str
 8   estilo_aprendizaje         950 non-null    str
 9   nota_final                 1000 non-null   float64
 10  aprobado                   1000 non-null   int64
dtypes: float64(5), int64(2), str(4)
memory usage: 108.0 KB
None
====================================================================================================
COLUMNAS CON VALORES NULOS
horas_sueno                  150
horario_estudio_preferido    100
estilo_aprendizaje            50
dtype: int64
====================================================================================================
PORCENTAJES DE COLUMNAS CON VALORES NULOS
horas_sueno                  15.0
horario_estudio_preferido    10.0
estilo_aprendizaje            5.0
dtype: float64
====================================================================================================
VALORES DUPLICADOS
0
====================================================================================================
CONTEO COLUMNAS CATEGORIAS
NIVEL_DIFICULTAD
nivel_dificultad
Medio      504
Fácil      313
Difícil    183
Name: count, dtype: int64
TIENE_TUTOR
tiene_tutor
No    597
Sí    403
Name: count, dtype: int64
HORARIO_ESTUDIO_PREFERIDO
horario_estudio_preferido
Noche     344
Tarde     337
Mañana    219
Name: count, dtype: int64
ESTILO_APRENDIZAJE
estilo_aprendizaje
Visual               363
Auditivo             254
Kinestésico          178
Lectura/Escritura    155
Name: count, dtype: int64
====================================================================================================
ESTADISTICOS CATEGÓRICOS

                          count unique     top freq
nivel_dificultad           1000      3   Medio  504
tiene_tutor                1000      2      No  597
horario_estudio_preferido   900      3   Noche  344
estilo_aprendizaje          950      4  Visual  363

ESTADISTICOS NUMÉRICAS

                        count       mean        std   min        25%        50%        75%    max
horas_estudio_semanal  1000.0  10.072366   4.852218   1.0   6.627548  10.000000  13.372452   25.0
nota_anterior          1000.0  69.885456  14.687697  30.0  59.882644  70.000000  80.117356  100.0
tasa_asistencia        1000.0  73.992079  18.195948  20.0  61.510192  75.000000  88.489808  100.0
horas_sueno             850.0   7.007670   1.444790   4.0   5.995341   7.020701   8.018834   10.0
edad                   1000.0  23.532000   3.476933  18.0  21.000000  24.000000  27.000000   29.0
nota_final             1000.0  71.441400   9.562078  30.0  64.775000  71.400000  77.900000  100.0
aprobado               1000.0   0.898000   0.302800   0.0   1.000000   1.000000   1.000000    1.0